project:
  type: website
  output-dir: docs

website:
  title: "Emily Miller"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
    right:
      - href: about.qmd
        text: "About"
      - href: art.qmd
        text: "Art & Poetry"
      - href: adventures.qmd
        text: "Adventures"
      - href: blog.qmd
        text: "Blog"
      - href: research.qmd
        text: "Research"
      - href: services.qmd
        text: "Services"
      - href: cv.qmd
        text: "Resume"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

