project:
  type: website
  output-dir: docs

website:
  title: "Emily Miller"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: research.qmd
        text: "Research"
      - href: cv.qmd
        text: "Resume"
      - text: "Creative"
        menu:
          - href: art.qmd
            text: "Art & Poetry"
          - href: adventures.qmd
            text: "Adventures"
    right:
      - icon: github
        href: https://github.com/rellimylime
        aria-label: "GitHub"

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full

editor: visual

